
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[247] =
    {   0,
        0,    0,   82,   81,   79,    1,   26,   47,   77,   81,
       81,   58,   61,   78,   70,   71,   56,   54,   76,   55,
       80,   57,   33,   69,   41,   48,   43,   31,   72,   73,
       81,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   74,   31,   75,   63,   42,    0,
       35,   37,    0,    0,    0,   28,   53,   46,    0,   68,
       51,   59,   49,   60,   50,   67,   66,   52,    0,   33,
       27,   64,   39,   44,   40,   65,   29,    0,   31,    0,
       29,    0,    0,   29,   31,   31,   31,   31,   31,    9,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   28,   28,    0,    0,   28,   28,   28,   38,
       34,   27,   29,   29,   29,    0,   36,   30,   30,    0,
       32,   29,   29,   62,   30,   31,   31,   31,   31,   11,
       15,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   28,   28,   28,   28,   28,   28,    0,    0,
       28,    0,   31,   16,   31,   31,   22,   19,   31,   31,
       31,   31,   31,   31,   31,   31,    7,   31,   28,   28,
       28,   28,    0,    0,    0,    8,   21,   31,    0,   31,
       31,   14,   20,   31,   31,   31,   10,    0,    0,   45,
       31,    3,    0,    0,   12,    6,   17,   23,   31,   25,

        0,   31,    0,    0,   31,   25,    0,   13,    0,    0,
       18,    0,    0,    0,    0,    0,    2,    0,    0,    0,
        0,    0,   24,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    0,    5,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    8,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   25,
       25,   25,   51,   52,   53,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    1,    1,
        1,    5,    3,    4,    1,    3,    1,    6,    1,    7,
        1,    1,    1,    1,    8,    5,    1,    1,    9,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    8,    1,    1
    } ;

static const flex_int16_t yy_base[265] =
    {   0,
        0,    0,  594,  635,  635,  635,  635,  570,   52,   23,
        0,  562,  574,    0,  635,  635,   40,   42,  635,   43,
      635,   48,   50,  635,   50,  552,   51,   69,  518,  635,
       68,   77,   41,   24,   45,   52,   53,   62,  519,   65,
       68,   66,   69,   56,  635,  111,  635,  635,  635,  121,
      635,  557,  552,  505,  496,  118,  635,  635,  526,  635,
      635,  635,  635,  635,  635,  635,  635,  635,  516,   98,
        0,  635,  635,  635,  635,  635,  120,  522,  122,   82,
      127,  507,  130,  132,  142,  147,  143,  144,  146,  157,
      161,  172,  189,  193,  197,  202,  207,  212,  211,  215,

      232,  254,  257,  264,  498,  500,  134,  154,  204,  635,
      511,    0,  635,  214,  222,  515,  635,  635,  265,  139,
      635,  274,  277,  501,  229,  288,  279,  290,  261,  265,
      267,  292,  273,  299,  275,  301,  304,  310,  307,  320,
      326,  322,  225,  362,  363,  370,  371,  378,  488,  485,
      635,  472,  348,  314,  317,  353,  334,  355,  370,  359,
      362,  375,  365,  379,  386,  388,  373,  393,  635,  429,
      635,  430,  480,  473,  493,  382,  399,  405,  423,  413,
      407,  411,  416,  431,  419,  427,  421,  485,  484,  635,
      437,  635,  151,  104,  424,  429,  433,  440,  454,    0,

      481,  456,  476,  242,  458,    0,  491,  446,  321,  481,
      449,    0,  170,  499,  385,  484,  635,  361,  378,  168,
      369,  262,  635,  314,  494,  418,  493,  486,  495,  505,
      497,  221,  335,  299,  287,  269,  265,  248,  209,  227,
      165,  118,  635,  130,  635,  635,  540,  542,  125,  546,
      552,  558,  564,  573,  579,  582,  588,  595,  601,  607,
      613,  622,   71,  626
    } ;

static const flex_int16_t yy_def[265] =
    {   0,
      246,    1,  246,  246,  246,  246,  246,  246,  247,  246,
      248,  246,  246,  249,  246,  246,  248,  246,  246,  246,
      246,  246,  250,  246,  246,  246,  246,  251,  246,  246,
      252,  251,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,  246,  253,  246,  246,  246,  247,
      246,  254,  254,  246,  246,  255,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      256,  246,  246,  246,  246,  246,  257,  258,   32,  246,
      259,  246,  252,  257,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,  260,  261,  246,  246,  255,  255,  255,  246,
      246,  256,  246,  257,  257,  258,  246,  246,   32,  246,
      246,  259,  259,  246,  252,   32,   32,   32,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  255,  260,  260,  255,  261,  261,  246,  246,
      246,  246,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  246,  260,
      246,  261,  246,  246,  246,  128,  128,  128,  258,  128,
      128,  128,  128,  128,  128,  128,  128,  246,  246,  246,
      128,  246,  258,  258,  128,  128,  128,  128,  128,  262,

      246,  128,  258,  258,  128,  262,  246,  128,  258,  258,
      128,  263,  258,  258,  264,  258,  246,  246,  264,  258,
      246,  258,  246,  258,  258,  258,  258,  258,  258,  258,
      258,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,    0,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246
    } ;

static const flex_int16_t yy_nxt[690] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,    4,   31,   28,
       32,   33,   28,   34,   35,   28,   28,   36,   28,   37,
       38,   28,   28,   39,   40,   41,   28,   42,   43,   44,
       45,   46,   47,   48,   51,   54,   62,   52,   60,   64,
       55,   66,   61,   88,   63,   65,   67,   69,   79,   70,
       68,   72,   73,   75,   76,   77,   77,   86,  215,   53,
       78,   77,   77,   87,   77,   79,   90,   89,   78,   79,
       77,   93,  102,   91,   80,   92,   79,   79,   95,   96,

       79,  120,   80,   53,   97,   98,   79,  100,  121,   79,
       79,  101,   79,   79,   99,   69,  117,   70,   77,   84,
       81,   85,   78,   51,   77,  107,   52,  113,   81,  118,
       79,  107,   59,  113,  113,  118,   80,  118,   78,  113,
      113,  151,  245,  118,  244,  113,  204,  151,   53,  118,
      118,  118,   80,  118,  118,  118,  118,  118,  120,  118,
      118,  151,  104,  117,  118,  121,   79,  151,  118,  109,
      118,  115,   53,  119,  118,  126,  127,  243,  123,  118,
      117,  125,  117,  115,  128,  118,   79,   79,   79,  129,
      130,   79,  203,  119,  119,  119,  118,  119,  119,  216,

      118,   79,  118,  222,  118,   79,  118,  131,  119,  118,
      118,  151,  119,  132,  118,  118,   79,  151,  118,  118,
      118,  113,  118,  119,  118,  118,  133,  113,  118,  113,
      134,  136,  151,   79,  233,  113,  118,   79,  151,  118,
      119,   79,  118,  135,  119,  118,   79,  138,  119,  137,
      234,   79,  242,  119,  117,  139,   79,  241,  119,   79,
      140,  118,  119,  119,  143,  115,  119,  118,   78,  141,
      143,  146,  118,  115,  117,   78,   79,  146,  118,  210,
      125,  113,   80,  119,  113,   78,  118,  113,   78,   80,
      113,  142,  118,  224,  157,  118,  240,  118,   79,   80,

      239,  118,   80,  118,  238,  119,   79,   79,  145,   79,
       79,   79,   79,   79,  159,  148,  119,  153,   79,   79,
       79,   79,  161,  154,  213,  123,  117,  158,  123,  225,
      119,  237,   79,  117,   79,  155,  156,   79,   79,  119,
      160,  119,  162,  236,   79,   79,   79,   79,  163,   79,
       79,  164,   79,   79,  165,   79,   79,  166,  167,   79,
       79,  168,   79,  177,  235,   79,   79,   79,   79,  169,
      169,   79,   79,   78,   78,  169,  169,  151,  171,   79,
       79,  179,   78,  151,  171,  171,  176,   80,   80,   78,
      178,  171,  223,   79,   79,  218,   80,  221,   79,   79,

       79,   79,  218,   80,   79,  180,  181,   79,   79,  182,
       79,  183,  184,  170,  170,   79,   79,  185,   79,   79,
       79,   79,  172,  186,   79,   79,  187,   79,   79,  172,
      117,   79,   79,   79,   79,  192,  169,  171,   79,   79,
       78,   78,  169,  171,   79,   79,  191,  195,  196,  227,
       79,   79,   79,   79,   80,   80,   79,   79,   79,   79,
      193,   79,   79,  197,   79,  198,   79,   79,  199,   79,
       79,  194,   79,   79,   79,   79,   79,   79,   79,   79,
      170,  172,   79,   79,  202,   79,   79,  205,  117,  208,
      211,   79,   79,  117,   79,   79,  117,  226,  117,   79,

       79,   79,   79,   79,   79,  117,  117,  117,  231,  117,
      232,  217,  212,  214,  207,  229,  201,  117,  200,  190,
      189,  188,  209,  175,  174,  173,  152,  117,  220,  228,
      111,  150,  149,  124,  117,  111,  110,  106,  105,  230,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   56,
       56,   71,   71,   71,   71,   79,   79,   52,   79,   79,
       79,   83,   52,   94,   83,   83,   83,  103,  103,   82,
      103,  103,  103,   53,   74,   53,   53,   53,   53,   53,
       53,   53,  108,   58,   57,  108,  108,  108,  112,  112,
      112,  114,   49,  246,  114,  114,  114,  116,  246,  246,

      246,  116,  116,  116,  122,  122,  246,  122,  122,  122,
      144,  144,  246,  144,  144,  144,  147,  147,  246,  147,
      147,  147,  206,  246,  206,  206,  206,  206,  206,  206,
      206,  219,  246,  219,    3,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246
    } ;

static const flex_int16_t yy_chk[690] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   10,   18,    9,   17,   20,
       10,   22,   17,   34,   18,   20,   22,   23,   34,   23,
       22,   25,   25,   27,   27,   31,   28,   33,  263,    9,
       28,   31,   28,   33,   32,   33,   36,   35,   32,   35,
       32,   38,   44,   36,   28,   37,   36,   37,   40,   41,

       44,   80,   32,    9,   41,   41,   38,   42,   80,   40,
       42,   43,   41,   43,   41,   70,  194,   70,   46,   31,
       28,   32,   46,   50,   46,   56,   50,   77,   32,   79,
       46,   56,  249,   77,   81,   79,   46,   83,   81,   84,
       81,  107,  244,   83,  242,   84,  194,  107,   50,   85,
       87,   88,   81,   89,   86,   85,   87,   88,  120,   89,
       86,  108,   46,  193,   90,  120,   79,  108,   91,   56,
       90,   77,   50,   79,   91,   85,   86,  241,   81,   92,
      220,   83,  213,   84,   87,   92,   85,   87,   88,   88,
       89,   86,  193,   85,   87,   88,   93,   89,   86,  213,

       94,   90,   93,  220,   95,   91,   94,   91,   90,   96,
       95,  109,   91,   92,   97,   96,   92,  109,   99,   98,
       97,  114,  100,   92,   99,   98,   93,  114,  100,  115,
       94,   96,  143,   93,  232,  115,  125,   94,  143,  101,
       93,   95,  125,   95,   94,  101,   96,   98,   95,   97,
      232,   97,  240,   96,  204,   99,   98,  239,   97,  100,
      100,  102,   99,   98,  103,  114,  100,  102,  103,  101,
      103,  104,  119,  115,  222,  104,  101,  104,  119,  204,
      125,  122,  103,  101,  123,  122,  127,  122,  123,  104,
      123,  102,  127,  222,  129,  126,  238,  128,  102,  122,

      237,  126,  123,  128,  236,  102,  129,  129,  103,  119,
      130,  130,  131,  131,  133,  104,  119,  126,  133,  133,
      135,  135,  135,  127,  209,  122,  224,  132,  123,  224,
      127,  235,  126,  209,  128,  128,  128,  132,  132,  126,
      134,  128,  136,  234,  134,  134,  136,  136,  137,  137,
      137,  138,  139,  139,  139,  138,  138,  140,  141,  154,
      154,  142,  155,  155,  233,  140,  140,  142,  142,  144,
      145,  141,  141,  144,  145,  144,  145,  146,  147,  157,
      157,  159,  147,  146,  147,  148,  153,  144,  145,  148,
      156,  148,  221,  153,  153,  219,  147,  218,  156,  156,

      158,  158,  215,  148,  160,  160,  161,  161,  161,  162,
      163,  163,  164,  144,  145,  159,  159,  165,  167,  167,
      162,  162,  147,  166,  164,  164,  168,  176,  176,  148,
      226,  165,  165,  166,  166,  179,  170,  172,  168,  168,
      170,  172,  170,  172,  177,  177,  178,  180,  181,  226,
      178,  178,  181,  181,  170,  172,  182,  182,  180,  180,
      179,  183,  183,  184,  185,  185,  187,  187,  186,  195,
      195,  179,  186,  186,  196,  196,  184,  184,  197,  197,
      170,  172,  191,  191,  191,  198,  198,  199,  203,  202,
      205,  208,  208,  210,  211,  211,  216,  225,  228,  199,

      199,  202,  202,  205,  205,  227,  225,  229,  230,  231,
      231,  214,  207,  210,  201,  228,  189,  230,  188,  175,
      174,  173,  203,  152,  150,  149,  124,  116,  216,  227,
      111,  106,  105,   82,   78,   69,   59,   55,   54,  229,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  248,
      248,  250,  250,  250,  250,  251,  251,   53,  251,  251,
      251,  252,   52,   39,  252,  252,  252,  253,  253,   29,
      253,  253,  253,  254,   26,  254,  254,  254,  254,  254,
      254,  254,  255,   13,   12,  255,  255,  255,  256,  256,
      256,  257,    8,    3,  257,  257,  257,  258,    0,    0,

        0,  258,  258,  258,  259,  259,    0,  259,  259,  259,
      260,  260,    0,  260,  260,  260,  261,  261,    0,  261,
      261,  261,  262,    0,  262,  262,  262,  262,  262,  262,
      262,  264,    0,  264,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "newcomp.l"
#line 2 "newcomp.l"
  int yylineno;

//Keywords
  #define WHILE 1
  #define VOID 2
  #define RETURN 3
  #define MAINFUNC 4
  #define BREAK 5
  #define CONTINUE 7
  #define IF 8
  #define INT 10
  #define CHAR 11
  #define UNSIGNED 12
  #define SIGNED 13
  #define LONG 14
  #define SHORT 15
  #define ELSE 16
  #define FOR 17
  #define STRUCT 18

//Identifier and Constant
  #define ID 20
  #define CONST 21

//Operators
  #define RELOP 22

//Logical
  #define LOGOP 26

//Assignment
  #define SIMPAS 29
  	//   =	Simple assignment operator.
  #define COMPAS 30

//Arithmetic
  #define ARITHOP 31
  #define PP 40
  	// ++
  #define MM 41
  	// --

//Bitwise Ops
  #define BITOP 42

// Miscelaneous tokens
  #define SEMICOLON 53
  #define BA1 54
  	// '(' bracket
  #define BA2 55
  	// ')' bracket
  #define BB1 56
  	// '[' bracket
  #define BB2 57
  	// ']' bracket
  #define BC1 58
  	// '{' bracket
  #define BC2 59
  	//'}' bracket
  #define COMMA 60
  	// ','
  #define Q 61
  	// Quote "
  #define SQ 62
  	// Single Quote '
  #define HEAD 63
  	// Header file
  #define ARR 64
	// Array
  #define SLC 65
	// Single comment '/'
  #define MLCO 66
  	// Multiline Comment Open '/*'
  #define MLCC 67
  	// Multilien Comment Close '*/'
  #define DEF 68
    // Macro
  #define PRINTF 69
  #define SCANF 70
  #define FUNC 71
  #define STRING 72
  #define INTCONST 73
  #define FLOATCONST 74
  #define CHARCONST 75
  #define INVALIDSTRING 76
  #define DOT 80

#line 764 "lex.yy.c"
#line 765 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 97 "newcomp.l"

#line 984 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 247 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 635 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 98 "newcomp.l"
{yylineno++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "newcomp.l"
return MAINFUNC;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "newcomp.l"
return MAINFUNC;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "newcomp.l"
return MAINFUNC;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "newcomp.l"
return MAINFUNC;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "newcomp.l"
return RETURN;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "newcomp.l"
return VOID;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "newcomp.l"
return BREAK;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "newcomp.l"
return IF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "newcomp.l"
return WHILE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "newcomp.l"
return FOR;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "newcomp.l"
return PRINTF;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "newcomp.l"
return CONTINUE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "newcomp.l"
return SCANF;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "newcomp.l"
return INT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "newcomp.l"
return CHAR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "newcomp.l"
return SIGNED;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "newcomp.l"
return UNSIGNED;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "newcomp.l"
return LONG;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "newcomp.l"
return SHORT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 118 "newcomp.l"
return CONST;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "newcomp.l"
return ELSE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 120 "newcomp.l"
return STRUCT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 122 "newcomp.l"
return HEAD;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 124 "newcomp.l"
return DEF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 127 "newcomp.l"
return 1000000;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 128 "newcomp.l"
return 333;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 129 "newcomp.l"
return 333;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 130 "newcomp.l"
return 333;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "newcomp.l"
return 333;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 132 "newcomp.l"
return ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 133 "newcomp.l"
return ARR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 134 "newcomp.l"
return INTCONST;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 135 "newcomp.l"
return FLOATCONST;
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 137 "newcomp.l"
return INVALIDSTRING;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "newcomp.l"
return FUNC;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "newcomp.l"
return STRING;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "newcomp.l"
return CHARCONST;
	YY_BREAK
case 39:
#line 145 "newcomp.l"
case 40:
#line 146 "newcomp.l"
case 41:
#line 147 "newcomp.l"
case 42:
#line 148 "newcomp.l"
case 43:
#line 149 "newcomp.l"
case 44:
YY_RULE_SETUP
#line 149 "newcomp.l"
{return RELOP;}
	YY_BREAK
case 45:
#line 152 "newcomp.l"
case 46:
#line 153 "newcomp.l"
case 47:
YY_RULE_SETUP
#line 153 "newcomp.l"
return LOGOP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "newcomp.l"
return SIMPAS;
	YY_BREAK
case 49:
#line 158 "newcomp.l"
case 50:
#line 159 "newcomp.l"
case 51:
#line 160 "newcomp.l"
case 52:
#line 161 "newcomp.l"
case 53:
YY_RULE_SETUP
#line 161 "newcomp.l"
return COMPAS;
	YY_BREAK
case 54:
#line 164 "newcomp.l"
case 55:
#line 165 "newcomp.l"
case 56:
#line 166 "newcomp.l"
case 57:
#line 167 "newcomp.l"
case 58:
YY_RULE_SETUP
#line 167 "newcomp.l"
return ARITHOP;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 169 "newcomp.l"
return PP;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 170 "newcomp.l"
return MM;
	YY_BREAK
case 61:
#line 173 "newcomp.l"
case 62:
#line 174 "newcomp.l"
case 63:
#line 175 "newcomp.l"
case 64:
#line 176 "newcomp.l"
case 65:
YY_RULE_SETUP
#line 176 "newcomp.l"
return BITOP;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "newcomp.l"
return SLC;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 179 "newcomp.l"
return MLCO;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 180 "newcomp.l"
return MLCC;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 182 "newcomp.l"
return SEMICOLON;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 183 "newcomp.l"
return BA1;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 184 "newcomp.l"
return BA2;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 185 "newcomp.l"
return BB1;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 186 "newcomp.l"
return BB2;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 187 "newcomp.l"
return BC1;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 188 "newcomp.l"
return BC2;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 189 "newcomp.l"
return COMMA;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 190 "newcomp.l"
return Q;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 191 "newcomp.l"
return SQ;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 192 "newcomp.l"
;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 193 "newcomp.l"
return DOT;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 194 "newcomp.l"
ECHO;
	YY_BREAK
#line 1391 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 247 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 247 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 246);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 194 "newcomp.l"


//Data Structure for the symbol and constant table
struct symbol
{
	char token[100];	// Name of the token
	char type[100];		// Token type: Identifier, string constant, floating point constant etc
}symbolTable[100000];

int i=0; // Number of symbols in the symbol table
int kw=0;

//Insert function for symbol/constant table
void symbolInsert(struct symbol table[], int index, char* tokenName, char* tokenType)
{
  strcpy(table[index].token, tokenName);
  strcpy(table[index].type, tokenType);
}

int main(void)
{
  int newToken, // The current token being processed
      j,k, // Iterators
      ba_c=0,ba_o=0,ba_l, // Number of open and close paranthesis, last line where the open parantesis was used
      bb_o=0,bb_c=0,bb_l, // Number of open and close square braces,  last line where the open sqaure brace was used
      bc_o=0,bc_c=0,bc_l, // Number of open and close curly braces,  last line where the open curly brace was used

      rep=0; // Flag to denote whether the current token is already in symbol table
  printf("LEXEME\t\t\tTYPE\t\t\t\t\tLINE NUMBER\n------------------------------------------------------------------------------");
  //Taking the input program
  yyin= fopen("test1.c","r");

  //Reading a single token from the program
  newToken = yylex();
  printf("\n");

  int mlc=0, // Flag to denote whether current token is part of a multiline comment
      slcline=0, // Line number of the single line comment
      mlcline; // Starting line number of multi line comment

  while(newToken)
  {
    rep = 0;

    if(yylineno==slcline) // If token belongs to a single line comment, ignore all the tokens
    {
      newToken=yylex();
      continue;
    }

    for(k=0;k<i;k++) // Checking whether token already exists in symbol table
    {
      if(!(strcmp(symbolTable[k].token,yytext)))
      {
        rep = 1;
        break;
      }
    }



    if(rep==0 && newToken!=65 && newToken!=66 && newToken!=67 && mlc==0)
    {
      strcpy(symbolTable[i].token,yytext);
    }
    if(newToken ==333 || newToken == 334 && mlc==0)
    {

      printf("%s\t\t\tInvalid identifier----------Line %d\n",yytext,yylineno);
    }

    if(newToken ==1 && mlc==0)
    {
      kw++;
      printf("%s\t\t\tWhile Loop\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken ==4 && mlc==0)
    {
      printf("%s\t\t\tMain function\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken ==8 && mlc==0)
    {
       kw++;
      printf("%s\t\t\tIf statement\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken ==16 && mlc==0)
    {
 kw++;
      printf("%s\t\t\tElse statement\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken ==17 && mlc==0)
    {
 kw++;
      printf("%s\t\t\tFor Loop\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken ==18 && mlc==0)
    {
 kw++;
      printf("%s\t\t\tStruct definition/declaration\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(((newToken>=1 && newToken<=15)) && mlc==0) // Keywords
    {
       kw++;
      printf("%s\t\t\tKeyword\t\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==20 && mlc==0) // Identifiers
    {
      if(rep == 0)
      {	symbolInsert(symbolTable, i, yytext, "ID");
      	i++;
      }
      printf("%s\t\t\tIdentifier\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==73 && mlc==0)
    {

      printf("%s\t\t\tInteger Constant\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==74 && mlc==0)
    {

      printf("%s\t\t\tFloating Point Constant\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==22 && mlc==0)
    {
      printf("%s\t\t\tRelational Operator\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==26 && mlc==0)
    {
      printf("%s\t\t\tLogical Operator\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==29 && mlc==0)
    {
      printf("%s\t\t\tSimple Assignment Operator\t\tLine %d\n",yytext,yylineno);
    }
    else if(newToken==30 && mlc==0)
    {
      printf("%s\t\t\tCompound Assignment Operator\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==31 && mlc==0)
    {
      printf("%s\t\t\tArithmetic Operator\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==42 && mlc==0)
    {
      printf("%s\t\t\tBitwise Operator\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==40 && mlc==0)
    {
      printf("%s\t\t\tIncrement Operator\t\t\tLine %d\n",yytext,yylineno);
    }
    else if(newToken==41 && mlc==0)
    {
      printf("%s\t\t\tDecrement Operator\t\t\tLine %d\n",yytext,yylineno);
    }


    else if((newToken>=53 && newToken<=62 ||newToken==80) && mlc==0)
    {
      if(newToken==54)
      {
        ba_o++;
	    ba_l = yylineno;
      }
      if(newToken==55)
        ba_c++;
      if(newToken==56)
      {
        bb_o++;
        bb_l = yylineno;
      }
      if(newToken==57)
        bb_c++;
      if(newToken==58)
      {
        bc_o++;
        bc_l = yylineno;
      }
      if(newToken==59)
        bc_c++;
        if(!newToken==60 && !newToken==53)
      printf("%s\t\t\tSpecial Character\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==63 && mlc==0)
    {
      printf("%s\tHeader\t\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==64 && mlc==0)
    {
      char id[100] = "";
      for(int t = 0; ; t++)
      {
        if(yytext[t] == '[')
          break;
        id[t] = yytext[t];
      }

      for(k=0;k<i;k++) // Checking whether token already exists in symbol table
      {
      	if(!(strcmp(symbolTable[k].token,id)))
      	{
        	rep = 1;
       		break;
      	}
      }

      if(rep == 0)
      {
        symbolInsert(symbolTable, i, id, "ID");
      	i++;
      }
      printf("%s\t\t\tArray Identfier\t\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==65 && mlc==0)
    {
      printf("%s\t\t\tSingle Line Comment\t\t\tLine %d\n",yytext,yylineno);
      slcline=yylineno;
    }

    else if(newToken==66)
    {
      mlc=1;
      printf("%s\t\t\tMulti Line Comment Start\t\t\tLine %d\n",yytext,yylineno);
      mlcline = yylineno;

    }

    else if(newToken==66 && mlc==1)
    {
      printf("%s\t\t\tNested multi Line Comment Start\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==67 && mlc==1)
    {
      mlc=0;
      printf("%s\t\t\tMulti Line Comment End\t\t\tLine %d\n",yytext,yylineno);
      mlcline=0;
    }

    else if(newToken==67 && mlc==0)
      printf("\n---------------ERROR : UNMATCHED NESTED END COMMENT-------------\n");

    else if(newToken==68 && mlc==0)
    {
      printf("%s\t\t\tPreprocessor Directive\t\t\t\tLine %d\n",yytext,yylineno);
      newToken=yylex();
      continue;
    }

    else if(newToken>=69 && newToken<=70 && mlc==0)
    {
      printf("%s\t\t\tPre Defined Function\t\t\tLine %d\n",yytext,yylineno);

    }

    else if(newToken==71 && mlc==0)
    {
      char id[100] = "";
      for(int t = 0; ; t++)
      {
        if(yytext[t] == '(')
          break;
        id[t] = yytext[t];
      }

      for(k=0;k<i;k++) // Checking whether token already exists in symbol table
      {
      	if(!(strcmp(symbolTable[k].token,id)))
      	{
        	rep = 1;
       		break;
      	}
      }

      if(rep == 0)
      {
        symbolInsert(symbolTable, i, id, "ID");
      	i++;
      }

      printf("%s\t\t\tUser Defined Function\t\t\tLine %d\n",yytext,yylineno);

    }

    else if(newToken==72 && mlc==0)
    {

      printf("%s\t\t\tString literal\t\t\t\tLine %d\n",yytext, yylineno);
    }

    else if(newToken==75 && mlc==0)
    {

      printf("%s\t\t\tCharacter Constant\t\t\tLine %d\n",yytext,yylineno);
    }

    else if(newToken==76 && mlc==0)
    {
	printf("\n--------------------ERROR : INCOMPLETE STRING starting at Line %d------------\n",yylineno);
    }

    newToken=yylex();
  }

  if(mlc==1)
    printf("\n--------------------ERROR : UNMATCHED COMMENT starting at Line %d------------\n",mlcline);

  if(ba_c<ba_o)
    printf("\n--------------------ERROR : UNMATCHED '(' at Line %d ------------------------\n",ba_l);

  if(bb_c<bb_o)
    printf("\n--------------------ERROR : UNMATCHED '[' at Line %d ------------------------\n",bb_l);

  if(bc_c<bc_o)
    printf("\n--------------------ERROR ! UNMATCHED '{' at Line %d ------------------------\n",bc_l);



    if(ba_c > ba_o){
    ba_o++;
      printf("\n-------------ERROR : UNMATCHED ')' at Line %d------------------\n", yylineno-1);}

    if(bb_c>bb_o)
      printf("\n-------------ERROR : UNMATCHED ']' at Line %d------------------\n", yylineno-1);

    if(bc_c>bc_o)
      printf("\n-------------ERROR : UNMATCHED '}' at Line %d------------------\n", yylineno-1);


  printf("\n------------Symbol Table---------------------\n\nSNo\tToken\t\tAttribute\n\n");

  for(j=0;j<i;j++)
    printf("%d\t%s\t\t< %s >\t\t\n",j+1,symbolTable[j].token,symbolTable[j].type);



	printf("\nNumber of keywords is: %d\n", kw);
  printf("Number of identifiers is: %d\n", i);
  return 0;
}

int yywrap(void)
{
	return 1;
}

